# Generated by Django 3.1 on 2020-08-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_adress',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='evaluation_about_bookstore',
            name='evaluation',
            field=models.IntegerField(default=1),
        ),
    ]
